sonar.projectKey=baemin_client
sonar.projectName=Baemin Client
sonar.sourceEncoding=UTF-8

sonar.sources=apis,app,components
sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,cypress/**/*.cy.ts

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/cypress/**
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/layout.tsx,cypress/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
