import type { Metadata } from "next";
import "./globals.scss";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import HeaderNav from "@/components/headerNav";
import { AppPreferencesProvider } from "@/components/appPreferences";

export const metadata: Metadata = {
  title: "Baemin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className="w-full min-h-screen font-sans">
        <AntdRegistry>
          <AppPreferencesProvider>
            <HeaderNav />
            <main className="pt-20">{children}</main>
          </AppPreferencesProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
